# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

optimLRTCpp <- function(p, ct, sf, y, z, DO_par, k, b) {
    .Call('_DECENT2_optimLRTCpp', PACKAGE = 'DECENT2', p, ct, sf, y, z, DO_par, k, b)
}

